# Generated by Django 3.1.2 on 2020-11-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_auto_20201102_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(default='No Link', max_length=2083),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='No Title', max_length=200),
        ),
    ]
