# Generated by Django 3.1.2 on 2020-11-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twillio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phoneModel',
        ),
    ]
