# Generated by Django 3.1.2 on 2020-11-26 19:10

import coupon.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='<function random_discount_code_generator at 0x10d0b93a0><function random_discount_generator at 0x10d0b99d0>', help_text='CODE50', max_length=25, unique=True)),
                ('valid_from', models.DateTimeField(default=datetime.datetime(2020, 11, 26, 19, 10, 20, 832247, tzinfo=utc))),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('discount', models.IntegerField(default=coupon.models.random_discount_generator, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=coupon.models.random_order_generator, max_length=10)),
                ('total_amount', models.IntegerField(default=5000)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
            ],
        ),
    ]
