# Generated by Django 3.1.2 on 2020-11-26 19:11

import coupon.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=coupon.models.random_discount_code_generator, help_text='CODE50', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 19, 11, 55, 438929, tzinfo=utc)),
        ),
    ]
