# Generated by Django 3.1.2 on 2020-11-27 04:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20201126_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 4, 14, 45, 620133, tzinfo=utc)),
        ),
    ]
